INSERT INTO TBL_CATEGORY ( NAME) VALUES ( 'Own Manufacturing')
INSERT INTO TBL_CATEGORY ( NAME) VALUES ( 'National')
INSERT INTO TBL_CATEGORY ( NAME) VALUES ( 'Imported')
INSERT INTO TBL_CATEGORY ( NAME) VALUES ( 'Premium')



INSERT INTO TBL_PRODUCT ( NAME, DESC,  PRICE, CATEGORY_ID, PROMOTION, NOVO) VALUES ('ASUS ROG Strix Scar 18','Intel Core i9-14900K' ,1000, 1, FALSE, TRUE)
INSERT INTO TBL_PRODUCT ( NAME, DESC, PRICE, CATEGORY_ID, PROMOTION, NOVO) VALUES ('Acer Nitro 5 AN515-58-54UH', 'Intel Core i5-14600KF', 800, 2, TRUE, TRUE)
INSERT INTO TBL_PRODUCT ( NAME, DESC, PRICE, CATEGORY_ID, PROMOTION, NOVO) VALUES ('Acer Nitro 5 AN515-58-54UH', 'Intel Core i5-13400', 700, 3, TRUE, FALSE)

